repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: check for uncreated migrations.
        entry: pipenv run ./manage.py makemigrations --check --dry-run
        types: ["python"]
        pass_filenames: false
        stages: [commit]
  - repo: local
    hooks:
      - id: isort
        language: system
        name: sort imports
        entry: pipenv run isort
        types: ["python"]
        stages: [commit]
  - repo: local
    hooks:
      - id: black
        language: system
        name: format files with black
        entry: pipenv run black
        types: ["python"]
        stages: [commit]
  - repo: local
    hooks:
      - id: flake8
        language: system
        name: check Python code style
        entry: pipenv run flake8
        types: ["python"]
        stages: [commit]
  - repo: local
    hooks:
      - id: tests
        language: system
        name: run tests
        entry: pipenv run ./manage.py test
        types: ["python"]
        pass_filenames: false
        stages: ["push"]
