# Generated by Django 4.0.4 on 2022-04-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskman', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='boardaccess',
            name='level',
            field=models.SmallIntegerField(choices=[(0, 'Owner'), (100, 'Admin'), (1000, 'Read Write'), (2000, 'Read Only'), (-1, 'None')], default=1000),
        ),
    ]
